print("Hello world!")
print("1st line")
print("2nd line")
print("3rd line")
print("4th line")
print("5th line -> comment:", "お疲れ様です！！！！！！！！")
print("6th line")
print("7th line")
print("8th line")
print("9th line")
print("10th line")
